import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Import the Poppins font
const poppins = Poppins({
  variable: "--font-poppins", // Define a custom CSS variable for the font
  subsets: ["latin"],         // Specify the subsets you need
  weight: ["400", "600", "700"], // Define the weights you need
});

export const metadata: Metadata = {
  title: "Nextgen Solution",  // Define your title
  description: "Generated by create next app",  // Define your description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children} {/* Render children in the body */}
      </body>
    </html>
  );
}
